feat: created send to wallet bookmark page
lifinance/widget pull request #135
Opened 2023-09-25 04:56 UTC by 0xsebn

Task: https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?modal=detail&selectedIssue=LF-4928&assignee=6398600d3c9bcd363977188e

2023-10-09 07:01 UTC, 0xsebn commented
For the first milestone where the goal is to display exchange warning message missing the 

-styling of the SendToWallet component (switching it to a clickable button instead of an input)
-Hiding the bookmarks button on the BookmarkLanding component
-removing unnecessary code from SendToWallet since its logic has been moved to BookmarkLanding

2023-10-10 12:05 UTC, dennyscode commented
Into how many pieces will this ticket be split? In the ticket itself, it´s not mentioned that we will do it in multiple iterations. 
But from your comments, it seems to be on point.

2023-10-10 15:01 UTC, chybisov requested changes

2023-10-16 16:44 UTC, chybisov approved these changes

2023-10-16 16:44 UTC, chybisov commented on packages/widget/src/components/SendToWalletButton/ShowSendToWalletButton.tsx
> +export const ShowSendToWalletButton: React.FC = () => {
ShowSendToWalletButton -> SendToWalletToggleButton

2023-10-16 22:19 UTC, 0xsebn commented
For any other person possibly reviewing this atm, hopped on a call with Eugene and he gave me some more comments. Will put the wait tag for now till I finish those

2024-01-23 13:35 UTC, chybisov commented
Finished in #168

2024-01-23 13:35 UTC, closed without merging