Lf 5279 cyber connect wallet
lifinance/widget pull request #147
Opened 2023-10-29 18:59 UTC by Abhikumar98

2023-10-29 19:00 UTC, Abhikumar98 commented on packages/widget/src/pages/SelectWalletPage/SelectWalletPage.tsx
> +      // navigateBack();
Uncomment the code

2023-10-30 13:31 UTC, chybisov requested changes

2023-10-30 13:34 UTC, Addminus requested changes

2023-10-30 13:34 UTC, Addminus commented on packages/wallet-management/src/wallets.ts
> +      name: 'Li.Fi',
all uppercase

2023-10-30 13:36 UTC, Addminus commented
lets fix icon as well
should be jumper

2023-11-09 12:32 UTC, chybisov requested changes
Please close this PR and use v2 branch.

2023-11-09 12:32 UTC, chybisov commented on packages/wallet-management/src/connectors/cyberConnectConnector.ts
> +    });
I'd ask why do we use Jumper related names/logos in the widget, but I guess it will take time to implement custom props from jumper to use here. 😕

2023-11-09 12:43 UTC, closed without merging