feat:rabby wallet added
lifinance/widget pull request #148
Opened 2023-10-31 04:41 UTC by 0xsebn

jira: https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?selectedIssue=LF-5463

Will update svg once Vilen posts it on figma

2023-11-01 06:17 UTC, 0xsebn commented
Added some details on the ticket
https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?assignee=6398600d3c9bcd363977188e&selectedIssue=LF-5463

2023-11-08 11:36 UTC, chybisov commented
> Added some details on the ticket https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?assignee=6398600d3c9bcd363977188e&selectedIssue=LF-5463

We need to find a way to determine when Rabby is installed, or it will compete with MM for window.ethereum. Especially in the new implementation.

2023-11-08 14:02 UTC, Addminus requested changes

2023-11-08 14:02 UTC, Addminus commented on packages/wallet-management/src/wallets.ts
> +    installed: async () => (window as any).ethereum,
looked at the wallet injection. for the installed hook
`(window as any).ethereum. isRabby` 
should work

2023-11-08 14:04 UTC, Addminus commented on packages/wallet-management/src/wallets.ts
> +    installed: async () => (window as any).ethereum,
actually rabby wallet injects also as `window.rabby` we should use that instead of the window.ethereum injection

2023-11-08 14:05 UTC, Addminus commented on packages/wallet-management/src/wallets.ts
> +    installed: async () => (window as any).ethereum,
so: installed just checks window.rabby

2023-11-08 14:05 UTC, Addminus commented on packages/wallet-management/src/wallets.ts
> +  (window as any).ethereum,
when going with window.rabby we should pass `(window as any).rabby)` as injection here

2023-11-09 13:39 UTC, closed without merging